config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root 'home#top'
  get 'home/about'
  get '/map_request', to: 'users#map', as: 'map_request'
  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  resources :users, except: [:new] do
    member do
      get :following, :followers
    end
    get :search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]
  
end

app/views/template/_book_comment.html.erb
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<table>
  <% book.book_comments.first(5).each do |book_comment| %>
    <% unless book_comment.id.nil? %>
      <tbody class="comment">
        <tr>
          <td class="avatar">
            <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
            <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
          </td>
          <td class="comment-author clearfix">
            <span class="comment-meta">
              <span class="comment-date"><%= book.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </td>
          <td class="comment-entry"><%= book_comment.comment %></td>
          <td>
            <% if book_comment.user == current_user%>
              <%= link_to "削除", book_book_comments_path(book_comment.book_id, comment: book_comment.id), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  <% end %>
</table>
<div class="collapse" id="collapseExample">
  <table>
    <% book.book_comments.offset(5).each do |book_comment| %>
    <tbody class="comment">
      <tr>
        <td class="avatar">
          <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
          <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
        </td>
        <td class="comment-author clearfix">
          <span class="comment-meta">
            <span class="comment-date"><%= book.created_at.strftime('%Y/%m/%d') %></span>
          </span>
        </td>
        <td class="comment-entry"><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user%>
            <%= link_to "削除", book_book_comments_path(book_comment.book_id, comment: book_comment.id), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/template/_book_index.html.erb
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', class: "", fallback: "no_image.jpeg", size: "40x40" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td id="favorite_<%= book.id %>">
          <%= render 'template/like', book: book %>
        </td>
        <td>
          <i class="far fa-comments"></i>
          <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/template/_comment_form.html.erb
<%= form_with(model: [book, book_comment], url: book_book_comments_path(@book) ) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows:'5', class: "form-control js-form-validate",placeholder: "コメントをここに" %>
    </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right form-submit js-disabled-submit" %>
  <%= javascript_include_tag "app.js" %>
<% end %>
      
    

app/views/template/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/template/_follow_form.html.erb
<div id="follow_form">
<% if current_user.already_following?(user) %>
  <%= render 'template/unfollow', user: user %>
<% else %>
  <%= render 'template/follow', user: user %>
<% end %>
</div>

app/views/template/_like.html.erb
<% if current_user.already_favorited?(book) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
  <%= book.favorites.count %>
  <% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="far fa-heart"></i>
  <% end %>
  <%= book.favorites.count %>
<% end %>

app/views/template/_seach.html.erb
<%= form_tag(search_users_path, :method => 'get') do %>
    <%= select_tag(:option, options_for_select([["user", "1"],["book","2"]]))%> 
    <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search' %>
<% end %>

app/views/template/_search.html.erb
<%= form_tag(search_users_path, :method => 'get') do %>
    <%= select_tag(:option, options_for_select([["user", "1"],["book", "2"]]))%> 
    <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search' %>
<% end %>

app/views/template/_sidemenu.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
  <div class="profile-container">
    <%= attachment_image_tag user, :profile_image, format: 'jpeg', class: "", fallback: "no_image.jpeg", size: "100x100" %>
    <table class="table">
      <thead>
        <tr>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>name</td>
          <td><%= user.name %></td>
        </tr>
        <tr>
          <td>introduction</td>
          <td><%= user.introduction %></td>
        </tr>
        <tr>
          <td>follows</td>
          <td><%= render 'template/stats', user: user %></td>
        </tr>
        <tr>
          <td>follower</td>
          <td><%= render 'template/stats_followers', user: user %></td>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <% if user.id == current_user.id %>
        <p>
          <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18309" %>
        </p>
      <% else %>
          <%= render 'template/follow_form', user: user %>
      <% end %>
    </div>
  </div>
  <h2>New book</h2>
  <%= form_for(book) do |f| %>
    <% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <h4>Title</h4>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>
    <br>
    <div class="row">
      <h4>Opinion</h4>
      <%= f.text_area :body, class:"form-control col-xs-12", rows:"3" %>
    </div>
    <hr>
    <div class="row">
      <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
    </div>
  <% end %>
</div>

app/views/template/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
  </a>
</div>

app/views/template/_stats_followers.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </a>
</div>

app/views/template/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/template/_user_index.html.erb
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, format: 'jpeg', class: "", fallback: "no_image.jpeg", size: "40x40" %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% unless user.id == current_user.id %>
            <%= render 'template/follow_form', user: user %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>