config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root 'home#top'
  get 'home/about'
  get '/map_request', to: 'users#map', as: 'map_request'
  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  resources :users, except: [:new] do
    member do
      get :following, :followers
    end
    get :search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse clearfix">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' Home', user_path(current_user.id), {class: "glyphicon glyphicon-home home"} %></li>
              <li><%= link_to ' Users', users_path, {class: "glyphicon glyphicon-user users"} %></li>
              <li><%= link_to ' Books', books_path, {class: "glyphicon glyphicon-book books"} %></li>
              <li><%= link_to ' logout', destroy_user_session_path, {method: :delete, class: "glyphicon glyphicon-log-out logout"} %></li>
            <% else %>
              <li><%= link_to ' Home', root_path, {class: "glyphicon glyphicon-home home"} %></li>
              <li><%= link_to ' About', home_about_path, {class: "glyphicon glyphicon-link"} %></li>
              <li><%= link_to ' sign up', new_user_registration_path, {class: "glyphicon glyphicon-edit"} %></li>
              <li><%= link_to ' login', new_user_session_path, {class: "glyphicon glyphicon-log-in"} %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <% if user_signed_in? %>
    <div class="container">
      <div class="row">
        <div class="search">
          <%= render 'template/search' %>
        </div>
      </div>
    </div>
    <% end %>


    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>